### ISSUE TITLE
Make this repo a pointer to openssh-hpn-isshd

### ISSUE THREAD

**Issue by jbasney** [set-element/InstrumentedSSHD#2]
I think https://github.com/set-element/InstrumentedSSHD has been obsoleted by https://github.com/set-element/openssh-hpn-isshd now, so it's be great for InstrumentedSSHD to redirect to openssh-hpn-isshd or otherwise make it obvious that we should be using the current version. Thanks!

**Comment by set-element** [comment]
This should be more or less resolved.  The code is still there for neurotic historical reasons, but hopefully sufficient indicators are in place to indicate the dead nature of the branches.

If you think that more is necessary, I am happy to take a stronger measure.

thanks!
scott
